---
- name: Fill metadata of the current snapshot
  ansible.builtin.template:
    src: files/info.xml.j2
    dest: /.snapshots/1/info.xml
    mode: "0600"
    force: false
  vars:
    date_utc: "{{ now(utc=True, fmt='%Y-%m-%d %H:%M:%S') }}"

- name: Ensure correct permissions on /.snapshots
  ansible.builtin.file:
    path: /.snapshots
    owner: root
    group: root
    mode: "0750"

- name: Enable btrfs quota support
  ansible.builtin.command: btrfs quota enable /
  changed_when: false

- name: Create qgroup for cleanup algorithms
  ansible.builtin.command: btrfs qgroup create 1/0 /
  register: snapper_qgroup_result
  changed_when: snapper_qgroup_result.rc == 1
  failed_when: false

- name: Init snapper config
  ansible.builtin.copy:
    src: /usr/share/snapper/config-templates/default
    dest: /etc/snapper/configs/root
    force: false
    mode: "0644"

- name: Set qgroup for snapper cleanup algorithms
  ansible.builtin.lineinfile:
    path: /etc/snapper/configs/root
    regexp: ^QGROUP=
    line: QGROUP="1/0"

- name: Enable root snapper configuration
  ansible.builtin.lineinfile:
    path: /etc/default/snapper
    regexp: ^SNAPPER_CONFIGS=
    line: SNAPPER_CONFIGS="root"

- name: Enable btrfsmaintenance timers
  ansible.builtin.command: /usr/share/btrfsmaintenance/btrfsmaintenance-refresh-cron.sh systemd-timer
  args:
    creates: /etc/systemd/system/timers.target.wants/btrfs-scrub.timer
