---
- name: Lookup keyfiles
  ansible.builtin.find:
    paths: /etc/keys
    patterns: "*.key"
  register: boot_keys

- name: Enable disk encryption
  when: boot_keys.files | length > 0
  block:
    - name: Enable grub luks support
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: ^GRUB_ENABLE_CRYPTODISK=
        line: GRUB_ENABLE_CRYPTODISK=y

    - name: Secure permissions for keyfiles
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: file
        mode: "0400"
      with_items: "{{ boot_keys.files }}"

    - name: Change permission policy for initramfs
      ansible.builtin.lineinfile:
        path: /etc/initramfs-tools/initramfs.conf
        regexp: ^UMASK=
        line: UMASK=0077

    - name: Setup keyfile pattern for initramfs
      ansible.builtin.lineinfile:
        path: /etc/cryptsetup-initramfs/conf-hook
        regexp: ^KEYFILE_PATTERN=
        line: KEYFILE_PATTERN="/etc/keys/*.key"
