---
- name: Set a hostname
  ansible.builtin.copy:
    content: "{{ hostname }}"
    dest: /etc/hostname
    mode: "0644"

- name: Symlink /etc/resolv.conf on next boot
  ansible.builtin.copy:
    src: symlink-stub-resolv.conf
    dest: /etc/tmpfiles.d/symlink-stub-resolv.conf
    mode: "0644"

- name: Add resolve to hosts in nsswitch.conf
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: "^hosts:"
    line: "hosts:          files mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns"

- name: Enable systemd-resolved
  ansible.builtin.systemd: name=systemd-resolved enabled=yes
