---
- name: Copy apt sources list
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: "0644"

- name: Import custom obs repo key
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/home:/mkrwc:/debian/Debian_11/Release.key
    state: present

- name: Add obs custom repo
  ansible.builtin.apt_repository:
    repo: deb https://download.opensuse.org/repositories/home:/mkrwc:/debian/Debian_11 ./
    filename: obs-mkrwc-debian
    state: present

- name: Update repos
  ansible.builtin.apt:
    update_cache: true

- name: Run dist upgrade
  ansible.builtin.apt:
    upgrade: dist

- name: Disable apt recommends and suggests
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/01norecommend
    create: true
    block: |
      APT::Install-Suggests "0";
      APT::Install-Recommends "0";
    mode: "0644"

- name: Create /usr/lib/sysimage directory
  ansible.builtin.file:
    path: /usr/lib/sysimage
    state: directory
    mode: "0755"

- name: Relocate dpkg files to /usr for rollbacks
  ansible.builtin.command: mv /var/lib/dpkg /usr/lib/sysimage/
  args:
    creates: /usr/lib/sysimage/dpkg

- name: Symlink to new dpkg location
  ansible.builtin.file:
    src: /usr/lib/sysimage/dpkg
    dest: /var/lib/dpkg
    state: link

- import_tasks: packages.yml
