---
- name: Install hardware stack
  ansible.builtin.apt:
    state: present
    pkg:
      - amd64-microcode
      - firmware-iwlwifi
      - firmware-realtek
      - firmware-atheros
      - firmware-linux
      - intel-microcode
      - linux-image-amd64
    default_release: "{{ backported_hardware_stack | ternary(debian_release + '-backports', debian_release) }}"

- name: Install packages
  ansible.builtin.apt:
    state: present
    pkg:
      - adw-gtk-theme
      - avahi-daemon
      - bash-completion
      - bluez
      - btrfs-progs
      - btrfsmaintenance
      - cryptsetup-initramfs
      - cups
      - cups-pk-helper
      - distrobox
      - earlyoom
      - ffmpegthumbnailer
      - fonts-iosevka
      - fonts-noto
      - fonts-noto-color-emoji
      - fwupd-amd64-signed
      - gdm3
      - gnome-control-center
      - gnome-disk-utility
      - gnome-online-accounts
      - gnome-session
      - gnome-software
      - gnome-software-plugin-flatpak
      - gnome-system-monitor
      - gnome-terminal
      - grub-efi-amd64
      - grub-efi-amd64-signed
      - gvfs-backends
      - libblockdev-crypto2 # unlock encrypted drives from nautilus
      - libcanberra-pulse # gnome-control-center sound panel
      - libgdk-pixbuf2.0-bin # nautilus thumbnails
      - libpam-gnome-keyring # auto-unlock keyring
      - libspa-0.2-bluetooth
      - locales
      - malcontent # gnome-control-center applications panel
      - mesa-utils
      - nautilus
      - nautilus-share
      - network-manager
      - network-manager-openvpn-gnome
      - openssh-client
      - plymouth-themes
      - powermgmt-base # for unattended-upgrades
      - powertop
      - samba
      - shim-signed
      - smartmontools
      - snapper
      - sudo
      - systemd-timesyncd
      - systemd-zram-generator
      - tlp-rdw
      - uidmap # distrobox, creating new boxes
      - unattended-upgrades
      - unzip
      - xdg-desktop-portal-gtk
      - xdg-user-dirs-gtk
      - xfsprogs

- name: Install backported packages
  ansible.builtin.apt:
    state: present
    pkg:
      - pipewire-pulse
      - wireplumber
    default_release: "{{ debian_release + '-backports' }}"

# need to be installed after grub package
- name: Install grub snapshots/rollback support
  ansible.builtin.apt:
    state: present
    pkg:
      - grub-btrfs
      - siduction-btrfs

# installed separately since 3rd party server can fail
- name: Install ms core fonts
  ansible.builtin.apt:
    name: ttf-mscorefonts-installer
  failed_when: false
