---
name: Build and release live ISO image
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: false
jobs:
  build-liveiso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set version variable
        id: set_version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          fi

      - name: Create build environment
        uses: docker/build-push-action@v6
        with:
          tags: debian-gsd:latest
          context: ./liveiso
          push: false

      - name: Run build script
        uses: addnab/docker-run-action@v3
        with:
          image: debian-gsd:latest
          options: --privileged -v ${{ github.workspace }}/out:/image/out
          run: /image/build.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.set_version.outputs.VERSION }}
          tag_name: liveiso-${{ steps.set_version.outputs.VERSION }}
          files: out/debian-gsd-amd64.hybrid.iso
