---
name: Lint files
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint ansible files
        uses: ansible-community/ansible-lint-action@v6.11.0
        with:
          path: "ansible/"
