---
name: Lint files
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint ansible files
        uses: ansible/ansible-lint@v25
        with:
          working_directory: "ansible/"
